---
language: node_js

node_js:
  - "12"

cache: npm

script:
  - npm install
  - npm run lint
  - npm test

before_install:
  - mkdir AllPublicXML
  - mkdir AllPublicXML/NCT0337xxxx
  - mv spec/data/NCT03377387.xml AllPublicXML/NCT0337xxxx
  - cd spec/data
  - curl https://storage.googleapis.com/ig-build/org.hl7.fhir.validator.jar  --output org.hl7.fhir.validator.jar

