---
language: node_js

node_js:
  - "12"

cache: npm

script:
  - npm install
  - npm install codecov -g
  - npm run lint
  - npm run-script coverage

before_install:
  - mkdir AllPublicXML
  - mkdir AllPublicXML/NCT0337xxxx
  - mv spec/data/NCT03377387.xml AllPublicXML/NCT0337xxxx

after_success:
  - codecov
